version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=db_tt_aluxion
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
    ports:
      - '5444:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@localhost.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5050:80'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      - PORT=${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
